name: Add new issues to triage column

on:
  issues:
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION: ethereum
  PROJECT_NUMBER: 43
  DRY_RUN: true

jobs:
  triage_issues:
    runs-on: ubuntu-latest
    if: join(github.event.issue.labels) == ''
    steps:
      - name: Retrieve the content of all columns on the board
        env:
          ORGANIZATION: ${{ env.ORGANIZATION }}
          PROJECT_NUMBER: ${{ env.PROJECT_NUMBER }}
        run: |
          gh api graphql --raw-field query='
            query($org: String!, $number: Int!) {
              organization(login: $org) {
                project(number: $number) {
                  columns(first: 10) {
                    nodes {
                      id,
                      name
                    }
                  }
                }
              }
            }' --raw-field organization="$ORGANIZATION" --field project_number="$PROJECT_NUMBER" >> project_data.json
          echo 'COLUMN_ID='$(jq '.data.organization.project.columns.nodes[] | select(.name == "Triage") | .id' project_data.json) >> $GITHUB_ENV
          echo 'COLUMN_NAME='$(jq '.data.organization.project.columns.nodes[] | select(.name == "Triage") | .name' project_data.json) >> $GITHUB_ENV
      - name: Add issue#${{ github.event.issue.number }} to Triage column
        env:
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_NUMBER: ${{ env.PROJECT_NUMBER }}
        run: |
          if [ ${{ env.DRY_RUN }} ]; then
            echo "Adding issue: ${{ github.event.issue.number }} to column $COLUMN_NAME in project $PROJECT_NUMBER"
          else
            gh api graphql --raw-field query='
              mutation($column: ID!, $issue: ID!) {
                addProjectCard(input: {
                  projectColumnId: $column,
                  contentId: $issue
                }) { clientMutationId }
              }' --raw-field column=$COLUMN_ID --raw-field issue=$ISSUE_ID --silent
          fi
